### ISSUE TITLE
Feed section not loading from another page except home.

### ISSUE THREAD

**Issue by lsahmed** [aaqaishtyaq/world#1]
Your Feed page is only loading from home page. If you open another page for example : you are on travel page then you click feed from the navbar it goes to ```aaqa.dev/travel(or any page)/rss.xml``` not ```aaqa.dev/rss.xml.```

![Screenshot 2024-03-06 151034](https://github.com/aaqaishtyaq/world/assets/85559104/618ec23a-1775-4d58-a398-b1a6bf7080b4)

**Comment by aaqaishtyaq** [comment]
Fixed by #2. Thank you for the contribution
